apm install  atom-material-ui && \
apm install  atom-beautify && \
apm install atom-clock && \
apm install atom-ide-ui && \
apm install autocomplete-python && \
apm install file-icons && \
apm install git-control && \
apm install minimap && \
apm install language-markdown && \
apm install language-nginx && \
apm install markdown-preview-plus && \
apm install markdown-writer && \
apm install platformio-ide-terminal && \
apm install pretty-json && \
apm install vim-mode-plus && \
apm install relative-numbers && \
apm install color-picker && \
apm install autocomplete-paths && \
apm install tree-view-git-statusa && \
apm install emmet && \
apm install pigments && \
apm install docblockr && \
apm install script && \
apm install merge-conflicts && \
apm install python-tools && \
apm install python-indent && \
apm install language-babel && \
apm install autocomplete-css && \
apm install autocomplete-modules && \
apm install git-plus && \
apm install brewser-plus && \
apm install git-time-machine && \
apm install autocomplete-python && \
apm install hydrogen && \
apm install hyperclick && \
apm install go-plus && \
apm install language-docker
